<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="5" total="16" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="FREE CRM Application Test Automation Test Suite" duration-ms="545409" started-at="2019-11-25T14:56:01 BDT" finished-at="2019-11-25T15:05:07 BDT">
    <groups>
    </groups>
    <test name="Free CRM App Test Cases" duration-ms="545409" started-at="2019-11-25T14:56:01 BDT" finished-at="2019-11-25T15:05:07 BDT">
      <class name="com.demo.qa.testCases.ContactPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9791" started-at="2019-11-25T14:58:26 BDT" finished-at="2019-11-25T14:58:35 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactsPageLabel()[pri:1, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="verifyContactsPageLabel" duration-ms="22483" started-at="2019-11-25T14:58:35 BDT" finished-at="2019-11-25T14:58:58 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactsPageLabel -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="627" started-at="2019-11-25T14:58:58 BDT" finished-at="2019-11-25T14:58:58 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="14763" started-at="2019-11-25T14:58:58 BDT" finished-at="2019-11-25T14:59:13 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="selectSingleContactsTest()[pri:2, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="selectSingleContactsTest" duration-ms="33379" retried="true" started-at="2019-11-25T14:59:13 BDT" finished-at="2019-11-25T14:59:47 BDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[contact is not selected did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: contact is not selected did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.demo.qa.testCases.ContactPageTest.selectSingleContactsTest(ContactPageTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectSingleContactsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="4904" started-at="2019-11-25T14:59:47 BDT" finished-at="2019-11-25T14:59:51 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9721" started-at="2019-11-25T14:59:51 BDT" finished-at="2019-11-25T15:00:01 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="selectSingleContactsTest()[pri:2, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="selectSingleContactsTest" duration-ms="29015" started-at="2019-11-25T15:00:01 BDT" finished-at="2019-11-25T15:00:30 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectSingleContactsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="678" started-at="2019-11-25T15:00:30 BDT" finished-at="2019-11-25T15:00:31 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="10134" started-at="2019-11-25T15:00:31 BDT" finished-at="2019-11-25T15:00:41 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyNewContactPageLabelTest()[pri:3, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="verifyNewContactPageLabelTest" duration-ms="8372" started-at="2019-11-25T15:00:41 BDT" finished-at="2019-11-25T15:00:49 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNewContactPageLabelTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="687" started-at="2019-11-25T15:00:49 BDT" finished-at="2019-11-25T15:00:50 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="11631" started-at="2019-11-25T15:00:51 BDT" finished-at="2019-11-25T15:01:02 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="65486" retried="true" started-at="2019-11-25T15:01:02 BDT" data-provider="ContactData" finished-at="2019-11-25T15:02:08 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Akif]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ahmed]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.qa.base.BasePage.doSendKeys(BasePage.java:24)
at com.demo.qa.pages.ContactsPage.createNewContact(ContactsPage.java:68)
at com.demo.qa.testCases.ContactPageTest.createNewContactTest(ContactPageTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="622" started-at="2019-11-25T15:02:08 BDT" finished-at="2019-11-25T15:02:08 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9033" started-at="2019-11-25T15:02:08 BDT" finished-at="2019-11-25T15:02:17 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="24984" started-at="2019-11-25T15:02:17 BDT" data-provider="ContactData" finished-at="2019-11-25T15:02:42 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Akif]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ahmed]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="675" started-at="2019-11-25T15:02:42 BDT" finished-at="2019-11-25T15:02:43 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9992" started-at="2019-11-25T15:02:43 BDT" finished-at="2019-11-25T15:02:53 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="26008" retried="true" started-at="2019-11-25T15:02:53 BDT" data-provider="ContactData" finished-at="2019-11-25T15:03:19 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kashfa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chowdhury]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no contact has been created did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no contact has been created did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.demo.qa.testCases.ContactPageTest.createNewContactTest(ContactPageTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="691" started-at="2019-11-25T15:03:19 BDT" finished-at="2019-11-25T15:03:20 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9316" started-at="2019-11-25T15:03:20 BDT" finished-at="2019-11-25T15:03:29 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="25018" retried="true" started-at="2019-11-25T15:03:29 BDT" data-provider="ContactData" finished-at="2019-11-25T15:03:54 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kashfa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chowdhury]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no contact has been created did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no contact has been created did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.demo.qa.testCases.ContactPageTest.createNewContactTest(ContactPageTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="664" started-at="2019-11-25T15:03:54 BDT" finished-at="2019-11-25T15:03:55 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="10911" started-at="2019-11-25T15:03:55 BDT" finished-at="2019-11-25T15:04:06 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="25266" retried="true" started-at="2019-11-25T15:04:06 BDT" data-provider="ContactData" finished-at="2019-11-25T15:04:31 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kashfa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chowdhury]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no contact has been created did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no contact has been created did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.demo.qa.testCases.ContactPageTest.createNewContactTest(ContactPageTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="669" started-at="2019-11-25T15:04:31 BDT" finished-at="2019-11-25T15:04:32 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="setUp" is-config="true" duration-ms="9589" started-at="2019-11-25T15:04:32 BDT" finished-at="2019-11-25T15:04:41 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createNewContactTest(java.lang.String, java.lang.String)[pri:4, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="createNewContactTest" duration-ms="24787" started-at="2019-11-25T15:04:41 BDT" data-provider="ContactData" finished-at="2019-11-25T15:05:06 BDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kashfa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chowdhury]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[no contact has been created did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: no contact has been created did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.demo.qa.testCases.ContactPageTest.createNewContactTest(ContactPageTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewContactTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.ContactPageTest@276438c9]" name="tearDown" is-config="true" duration-ms="678" started-at="2019-11-25T15:05:06 BDT" finished-at="2019-11-25T15:05:07 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.qa.testCases.ContactPageTest -->
      <class name="com.demo.qa.testCases.LogInPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="setUp" is-config="true" duration-ms="11896" started-at="2019-11-25T14:56:01 BDT" finished-at="2019-11-25T14:56:13 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="landingPageTitleTest()[pri:1, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="landingPageTitleTest" duration-ms="14" started-at="2019-11-25T14:56:13 BDT" finished-at="2019-11-25T14:56:13 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- landingPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="tearDown" is-config="true" duration-ms="615" started-at="2019-11-25T14:56:13 BDT" finished-at="2019-11-25T14:56:14 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="setUp" is-config="true" duration-ms="9020" started-at="2019-11-25T14:56:14 BDT" finished-at="2019-11-25T14:56:23 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="logoImageTest()[pri:2, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="logoImageTest" duration-ms="143" started-at="2019-11-25T14:56:23 BDT" finished-at="2019-11-25T14:56:23 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoImageTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="tearDown" is-config="true" duration-ms="4902" started-at="2019-11-25T14:56:23 BDT" finished-at="2019-11-25T14:56:28 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="setUp" is-config="true" duration-ms="10237" started-at="2019-11-25T14:56:28 BDT" finished-at="2019-11-25T14:56:38 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="logInTest()[pri:3, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="logInTest" duration-ms="16654" started-at="2019-11-25T14:56:38 BDT" finished-at="2019-11-25T14:56:55 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.LogInPageTest@166fa74d]" name="tearDown" is-config="true" duration-ms="619" started-at="2019-11-25T14:56:55 BDT" finished-at="2019-11-25T14:56:55 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.qa.testCases.LogInPageTest -->
      <class name="com.demo.qa.testCases.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="setUp" is-config="true" duration-ms="8877" started-at="2019-11-25T14:56:55 BDT" finished-at="2019-11-25T14:57:04 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyHomePageTitleTest()[pri:1, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="verifyHomePageTitleTest" duration-ms="15983" started-at="2019-11-25T14:57:04 BDT" finished-at="2019-11-25T14:57:20 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="tearDown" is-config="true" duration-ms="700" started-at="2019-11-25T14:57:20 BDT" finished-at="2019-11-25T14:57:21 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="setUp" is-config="true" duration-ms="9110" started-at="2019-11-25T14:57:21 BDT" finished-at="2019-11-25T14:57:30 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyUserNameTest()[pri:2, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="verifyUserNameTest" duration-ms="22837" started-at="2019-11-25T14:57:30 BDT" finished-at="2019-11-25T14:57:53 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserNameTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="tearDown" is-config="true" duration-ms="621" started-at="2019-11-25T14:57:53 BDT" finished-at="2019-11-25T14:57:54 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="setUp" is-config="true" duration-ms="8907" started-at="2019-11-25T14:57:54 BDT" finished-at="2019-11-25T14:58:03 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactsLinkTest()[pri:3, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="verifyContactsLinkTest" duration-ms="22391" started-at="2019-11-25T14:58:03 BDT" finished-at="2019-11-25T14:58:25 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactsLinkTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.demo.qa.testCases.HomePageTest@40f08448]" name="tearDown" is-config="true" duration-ms="614" started-at="2019-11-25T14:58:25 BDT" finished-at="2019-11-25T14:58:26 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.demo.qa.testCases.HomePageTest -->
    </test> <!-- Free CRM App Test Cases -->
  </suite> <!-- FREE CRM Application Test Automation Test Suite -->
</testng-results>
